/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class HelloWorld */

#ifndef _Included_HelloWorld
#define _Included_HelloWorld
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     HelloWorld
 * Method:    sayHello
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_HelloWorld_sayHello
  (JNIEnv *, jobject);

/*
 * Class:     HelloWorld
 * Method:    sayBye
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_HelloWorld_sayBye
  (JNIEnv *, jobject);

/*
 * Class:     HelloWorld
 * Method:    add
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_HelloWorld_add
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     HelloWorld
 * Method:    sub
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_HelloWorld_sub
  (JNIEnv *, jobject, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
